os:
  - linux
  # - osx
  # - windows

dist: xenial
sudo: require
language: cpp

script:
  - bash scripts/clean
  - bash scripts/configure 
  - bash scripts/build
  - bash scripts/run-unit-tests 

deploy:
  provider: releases
  api_key: "df91e078d1a9c32cf11ba754a3886642d6b34cd9"
  file: "bin/calculator"
  skip_cleanup: true
## Deploy only if the build is a tagged build
#   on:
#     tags: true
    
# end of file
