sudo: false

language: cpp

compiler:
  - gcc
  - clang
  
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7    
      - gcc-5
      - g++-5      

script:
  - bash scripts/clean
  - bash scripts/configure 
  - bash scripts/build
  - bash scripts/run-unit-tests 
