os:
  - linux
  # - osx
  # - windows

dist: xenial
sudo: require
language: cpp

script:
  - bash scripts/clean
  - bash scripts/configure 
  - bash scripts/build
  - bash scripts/run-unit-tests 

# before_deploy:
#    git tag `git rev-parse --short HEAD`

deploy:
  provider: releases
  api_key:
    secure: MJfXfPwmdHUrOYGsRXuqWiUgGHY5uiVCpxv11kyAAW9wSVU8k09FPOj2gkuiTQAGT5udQgAuz2zTZcch6GI1l2/iQDJjVrJTlwUBKiaSp9WACiAd2XZB4PY9AgyymHLsirK7FcSOzhXMBKh9Sf2fJw4jyl5znJsYXpGKSl7GPwtdapHaxbQM+M1vIMs1xtXDqvVEJwK+/XG+nf2j3N7NycjfSHCpjJniyeuZAJ0+Wq5R+ydE/nU6d3abprFfC0nuLhx0dNBWFNwvMNS5doLC9GowVEqcgd8xHe3FcxzHDmlw1qiLC49Zzgik9SJ/KqIFWmGcD+KoAb9i2K5jR9xpoDwnXYK0AZYbL+/QK2su70QVHM2KAy92nViKfihvKl4C9MaUZZX5hRT5HqECfWl2K4//C/2sGOCGXZ1dguhNj/D8mu23DpEfcofmfYY/6rwS5xRILj8XsDUs2v7utRkpFW16t5A2ce/GwJ6UShIK1hsl12bFkxnsA3Gl+qqtQsJqEuswolNiMrJozWmPqfAhMPZS9EuEJpFLMakt47Tmt2h58Iph7oY0D/z1WhWDsr4cPfA7S3Y2wQF7pzqT7nSsA5AldbrJg+dOAMcmoOw+PzbasJwT/rxBlg1w+vfbMviKiLIrMERMYWcIH8AZPAROblnksUhXDpTqn/jmROHWqu4=
  file: "bin/calculator"
  skip_cleanup: true
  overwrite: true
  # draft: true
  ## Deploy only if the build is a tagged build
  on:
     tags: true
    
# end of file
